# Generated by Django 4.0.3 on 2022-04-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
