# Generated by Django 4.0.3 on 2022-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='preview_des',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='product',
            name='medium',
            field=models.CharField(default='test', max_length=255, verbose_name='Short Descriptions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(default='test', max_length=200, verbose_name='Descriptions'),
            preserve_default=False,
        ),
    ]
