# Generated by Django 4.0.3 on 2022-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_rename_preview_des_product_artist_product_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.CharField(max_length=180, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='medium',
            field=models.CharField(max_length=180, verbose_name='Medium'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=150, verbose_name='size'),
        ),
    ]
