# Generated by Django 4.0.3 on 2022-04-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0012_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash'), ('NAGAD', 'NAGAD')], default='Cash on Delivery', max_length=30),
        ),
    ]
