# Generated by Django 4.0.3 on 2022-04-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0013_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='address1',
            new_name='bill_address',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='address2',
            new_name='ship_address',
        ),
    ]
