# Generated by Django 4.0.3 on 2022-04-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_rename_bill_address_billingaddress_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash')], default='Cash on Delivery', max_length=30),
        ),
    ]
